CREATE TABLE IF NOT EXISTS public.admin_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'coordinator' CHECK (role IN ('admin', 'coordinator')),
    school TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.relatos
    ADD COLUMN IF NOT EXISTS assigned_to UUID REFERENCES public.admin_profiles(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent'));

CREATE TABLE IF NOT EXISTS public.relato_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relato_id UUID NOT NULL REFERENCES public.relatos(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.admin_profiles(id),
    content TEXT NOT NULL CHECK (char_length(content) BETWEEN 2 AND 5000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.relato_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relato_id UUID NOT NULL REFERENCES public.relatos(id) ON DELETE CASCADE,
    author_id UUID NOT NULL REFERENCES public.admin_profiles(id),
    recipient_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 2 AND 10000),
    delivery_status TEXT NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed')),
    provider_id TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS relatos_admin_filters_idx ON public.relatos(status, tipo, severidade, data_criacao DESC);
CREATE INDEX IF NOT EXISTS relatos_assigned_to_idx ON public.relatos(assigned_to);
CREATE INDEX IF NOT EXISTS relato_notes_relato_idx ON public.relato_notes(relato_id, created_at DESC);
CREATE INDEX IF NOT EXISTS relato_responses_relato_idx ON public.relato_responses(relato_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_actor_idx ON public.audit_logs(actor_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.is_active_staff(user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.admin_profiles
        WHERE id = user_id AND active = TRUE
    );
$$;

CREATE OR REPLACE FUNCTION public.is_admin(user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.admin_profiles
        WHERE id = user_id AND active = TRUE AND role = 'admin'
    );
$$;

REVOKE ALL ON FUNCTION public.is_active_staff(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_admin(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_active_staff(UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(UUID) TO authenticated, service_role;

ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relato_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relato_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Staff can read own profile" ON public.admin_profiles;
CREATE POLICY "Staff can read own profile" ON public.admin_profiles
    FOR SELECT TO authenticated
    USING (id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "Admins manage profiles" ON public.admin_profiles;
CREATE POLICY "Admins manage profiles" ON public.admin_profiles
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Staff read reports" ON public.relatos;
CREATE POLICY "Staff read reports" ON public.relatos
    FOR SELECT TO authenticated
    USING (public.is_active_staff());

DROP POLICY IF EXISTS "Staff update reports" ON public.relatos;
CREATE POLICY "Staff update reports" ON public.relatos
    FOR UPDATE TO authenticated
    USING (public.is_active_staff())
    WITH CHECK (public.is_active_staff());

DROP POLICY IF EXISTS "Staff manage notes" ON public.relato_notes;
CREATE POLICY "Staff manage notes" ON public.relato_notes
    FOR ALL TO authenticated
    USING (public.is_active_staff())
    WITH CHECK (public.is_active_staff() AND author_id = auth.uid());

DROP POLICY IF EXISTS "Staff read responses" ON public.relato_responses;
CREATE POLICY "Staff read responses" ON public.relato_responses
    FOR SELECT TO authenticated
    USING (public.is_active_staff());

DROP POLICY IF EXISTS "Staff read audit logs" ON public.audit_logs;
CREATE POLICY "Staff read audit logs" ON public.audit_logs
    FOR SELECT TO authenticated
    USING (public.is_admin());

GRANT SELECT ON public.admin_profiles, public.relatos, public.relato_notes, public.relato_responses TO authenticated;
GRANT UPDATE ON public.relatos TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.relato_notes TO authenticated;
GRANT SELECT ON public.audit_logs TO authenticated;

COMMENT ON TABLE public.admin_profiles IS 'Authorized administrative portal users. Passwords remain exclusively in Supabase Auth.';
COMMENT ON TABLE public.relato_responses IS 'Immutable record of responses sent through the Resend integration.';