-- Reports flagged by the word filter are kept, but listed apart for review.
ALTER TABLE public.relatos
    ADD COLUMN IF NOT EXISTS suspeito BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS motivo_suspeita TEXT;

CREATE INDEX IF NOT EXISTS relatos_suspeito_data_idx ON public.relatos(suspeito, data_criacao DESC);

-- Submission rate limit. Stores only a salted hash of the origin, never the IP itself.
CREATE TABLE IF NOT EXISTS public.submission_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS submission_attempts_origin_idx ON public.submission_attempts(origin_hash, created_at DESC);

ALTER TABLE public.submission_attempts ENABLE ROW LEVEL SECURITY;
-- No policies on purpose: only the service role (edge functions) can read or write it.
